import io

from app.core.rag.common.string_utils import clean_markdown_block

VIDEO_EXTS = [".mp4", ".mov", ".avi", ".flv", ".mpeg", ".mpg", ".webm", ".wmv", ".3gp", ".3gpp", ".mkv"]


def chunk(filename, binary, lang, callback=None, vision_model=None, **kwargs):
    from app.core.rag.chunk import chunk_pipeline

    return chunk_pipeline(
        filename,
        binary=binary,
        lang=lang,
        callback=callback,
        vision_model=vision_model,
        **kwargs,
    )


def vision_llm_chunk(binary, vision_model, prompt=None, callback=None):
    """
    A simple wrapper to process image to markdown texts via VLM.

    Returns:
        Simple markdown texts generated by VLM.
    """
    callback = callback or (lambda prog, msg: None)

    image = binary
    text = ""

    try:
        with io.BytesIO() as img_binary:
            try:
                image.save(img_binary, format="JPEG")
            except Exception:
                img_binary.seek(0)
                img_binary.truncate()
                image.save(img_binary, format="PNG")

            img_binary.seek(0)
            description, _ = vision_model.describe_with_prompt(img_binary.read(), prompt)
            answer = clean_markdown_block(description)
            text += "\n" + answer
            return text

    except Exception as error:
        callback(-1, str(error))

    return ""
