"""202608311749

Revision ID: 73d8a571c745
Revises: 9641d3fb8322
Create Date: 2026-08-31 17:49:39.725597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '73d8a571c745'
down_revision = '9641d3fb8322'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column(
        'event_id', postgresql.UUID(as_uuid=True), nullable=False,
        server_default=sa.text('gen_random_uuid()')))
    op.alter_column('audit_logs', 'event_id', server_default=None)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_ts'), 'audit_logs', ['ts'], unique=False)
    op.create_unique_constraint('uq_audit_logs_event_id', 'audit_logs', ['event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_audit_logs_event_id', 'audit_logs', type_='unique')
    op.drop_index(op.f('ix_audit_logs_ts'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'event_id')
    # ### end Alembic commands ###
