"""202609231152

Revision ID: db6239770221
Revises: 73d8a571c745
Create Date: 2026-09-23 11:53:01.079719

"""
from alembic import op
import sqlalchemy as sa


revision = 'db6239770221'
down_revision = '73d8a571c745'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_acl_rules_triple', 'acl_rules', ['caller_service', 'target_service', 'endpoint'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_acl_rules_triple', 'acl_rules', type_='unique')
    # ### end Alembic commands ###
