import { resolve } from 'path'
import { existsSync, readdirSync, readFileSync } from 'fs'
import type { Plugin } from 'vite'

export interface VirtualMemoryBrickOptions {
  /** Project root directory, defaults to process.cwd() */
  root?: string
  /** Private package name */
  packageId?: string
  /** Entry file relative to root (resolved here when the private package is installed) */
  entry?: string
  /** Directory (relative to root) to scan for business code to collect exports needing a fallback */
  srcDir?: string
  /**
   * Override table of fallback values for specific exports: export name -> value expression string.
   * By default every named export falls back to an empty component that renders null;
   * if an export is actually an object/constant rather than a component, specify it here, e.g. { ReflectMemoryRef: '{}' }.
   */
  overrides?: Record<string, string>
}

const DEFAULT_PACKAGE_ID = '@redbear/memory-brick'

/**
 * Virtual fallback plugin for the private package @redbear/memory-brick.
 * - Installed: resolves the bare package name to the real entry.
 * - Not installed: scans business code for named imports of the package and dynamically
 *   generates a virtual module that provides only empty implementations, so builds still
 *   succeed in external environments where the private package is missing, without having
 *   to hand-maintain a list of fallback exports.
 */
export function virtualMemoryBrickPlugin(options: VirtualMemoryBrickOptions = {}): Plugin {
  const root = options.root ?? process.cwd()
  const packageId = options.packageId ?? DEFAULT_PACKAGE_ID
  const srcDir = resolve(root, options.srcDir ?? 'src')
  const overrides = options.overrides ?? {}

  const packageDir = resolve(root, 'node_modules', packageId)
  const entry = resolve(packageDir, options.entry ?? 'dist/index.js')
  const virtualId = '\0' + packageId
  // Whether the package is installed is fixed at build time; determine it once to avoid re-checking on every import resolution
  const packageInstalled = existsSync(packageDir)
  console.log(
    `[virtual-memory-brick] ${packageId} ${packageInstalled ? 'installed, using the real private package' : 'missing, using the virtual fallback module'}`,
  )

  return {
    name: 'virtual-memory-brick',
    enforce: 'pre',
    resolveId(id: string) {
      if (id !== packageId) return null
      return packageInstalled ? entry : virtualId
    },
    load(id: string) {
      if (id !== virtualId) return null
      const names = collectNamedImports(srcDir, packageId)
      return generateFallbackModule(names, overrides)
    },
  }
}

/** Recursively collect all runtime-needed identifiers named-imported from packageId under srcDir */
function collectNamedImports(srcDir: string, packageId: string): string[] {
  if (!existsSync(srcDir)) return []

  const escaped = packageId.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  // Matches `import [type] [Default,] [{ ... }] from '<pkg>'`; the braces exclude } to avoid matching across statements
  const importRe = new RegExp(
    `import\\s+(type\\s+)?(?:[\\w$]+\\s*,\\s*)?(?:\\{([^}]*)\\})?\\s*from\\s*['"]${escaped}['"]`,
    'g',
  )

  const names = new Set<string>()
  for (const file of walkSourceFiles(srcDir)) {
    const code = readFileSync(file, 'utf-8')
    let match: RegExpExecArray | null
    while ((match = importRe.exec(code)) !== null) {
      // A whole `import type { ... }`: types only, no runtime fallback needed
      if (match[1]) continue
      const braces = match[2]
      if (!braces) continue
      for (const raw of braces.split(',')) {
        const part = raw.trim()
        // Skip empty items and inline type imports `type Foo`
        if (!part || part.startsWith('type ')) continue
        // `Origin as Alias` only needs the original name Origin exported
        const name = part.split(/\s+as\s+/)[0].trim()
        if (name) names.add(name)
      }
    }
  }
  return [...names]
}

/** Recursively walk the directory and return all .ts/.tsx/.js/.jsx source file paths */
function walkSourceFiles(dir: string, files: string[] = []): string[] {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.') || entry.name === 'node_modules') continue
    const full = resolve(dir, entry.name)
    if (entry.isDirectory()) {
      walkSourceFiles(full, files)
    } else if (/\.[jt]sx?$/.test(entry.name)) {
      files.push(full)
    }
  }
  return files
}

/** Generate the virtual fallback module source from the collected export names */
function generateFallbackModule(names: string[], overrides: Record<string, string>): string {
  const lines = [
    '// This module is auto-generated by the virtual-memory-brick plugin when the private package is missing',
    'const FallbackComponent = null;',
    '// Fallback flag: lets runtime distinguish the virtual module from the real private package (which has no such export)',
    'export const __isFallback = true;',
  ]
  for (const name of names) {
    const value = overrides[name] ?? 'FallbackComponent'
    lines.push(`export const ${name} = ${value};`)
  }
  const defaultBody = names.length ? ` ${names.join(', ')} ` : ''
  lines.push(`export default {${defaultBody}};`)
  return lines.join('\n')
}
