"""Lightweight public exports for RedBear model resolution."""

from .contracts import (
    QWEN3_VL_EMBEDDING_DIMENSION,
    EmbeddingContent,
    EmbeddingPurpose,
    EmbeddingRequest,
    EmbeddingResult,
    ImageEmbeddingContent,
    LoadBalanceStrategy,
    ModelCapability,
    ModelConfigSnapshot,
    ModelKeySnapshot,
    ModelProvider,
    ModelRuntimeOptions,
    ModelType,
    PublicModelBindingSnapshot,
    RerankCandidateView,
    RerankQuery,
    RerankScore,
    ResolvedModelConfig,
    SupportedImageMediaType,
    TextEmbeddingContent,
)
from .errors import (
    InvalidProviderResponseError,
    ModelAccessDeniedError,
    ModelConfigInactiveError,
    ModelConfigNotFoundError,
    ModelCredentialNotFoundError,
    ModelUsageRecordError,
    ProviderDependencyMissingError,
    PublicCredentialUnavailableError,
    RedBearModelError,
    UnsupportedModelProviderError,
    UnsupportedMultimodalModelError,
)
from .ports import AsyncModelRegistryRepository, ModelRegistryRepository
from .providers.dashscope import is_qwen3_vl_embedding, is_qwen3_vl_reranker
from .resolver import (
    record_model_usage,
    record_model_usage_async,
    resolve_model,
    resolve_model_async,
)

__all__ = [
    "QWEN3_VL_EMBEDDING_DIMENSION",
    "AsyncModelRegistryRepository",
    "EmbeddingContent",
    "EmbeddingPurpose",
    "EmbeddingRequest",
    "EmbeddingResult",
    "ImageEmbeddingContent",
    "InvalidProviderResponseError",
    "LoadBalanceStrategy",
    "ModelAccessDeniedError",
    "ModelCapability",
    "ModelConfigInactiveError",
    "ModelConfigNotFoundError",
    "ModelConfigSnapshot",
    "ModelCredentialNotFoundError",
    "ModelKeySnapshot",
    "ModelProvider",
    "ModelRegistryRepository",
    "ModelRuntimeOptions",
    "ModelType",
    "ModelUsageRecordError",
    "ProviderDependencyMissingError",
    "PublicCredentialUnavailableError",
    "PublicModelBindingSnapshot",
    "RedBearModelError",
    "RerankCandidateView",
    "RerankQuery",
    "RerankScore",
    "ResolvedModelConfig",
    "SupportedImageMediaType",
    "TextEmbeddingContent",
    "UnsupportedModelProviderError",
    "UnsupportedMultimodalModelError",
    "is_qwen3_vl_embedding",
    "is_qwen3_vl_reranker",
    "record_model_usage",
    "record_model_usage_async",
    "resolve_model",
    "resolve_model_async",
]
