"""202609101720

Revision ID: 008506effb1a
Revises: 11172ee5d4fd
Create Date: 2026-09-10 09:21:17.562210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '008506effb1a'
down_revision: Union[str, None] = '11172ee5d4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_storage_outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.Text(), nullable=False),
    sa.Column('operation', sa.String(length=20), server_default='upsert', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('attempt_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('claim_token', sa.UUID(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(status = 'processed' AND processed_at IS NOT NULL AND failed_at IS NULL) OR (status = 'failed' AND failed_at IS NOT NULL AND processed_at IS NULL) OR (status IN ('pending', 'processing') AND processed_at IS NULL AND failed_at IS NULL)", name='ck_memory_outbox_terminal_times'),
    sa.CheckConstraint("(status = 'processing' AND locked_by IS NOT NULL AND claim_token IS NOT NULL AND locked_at IS NOT NULL AND heartbeat_at IS NOT NULL) OR (status <> 'processing' AND locked_by IS NULL AND claim_token IS NULL AND locked_at IS NULL AND heartbeat_at IS NULL)", name='ck_memory_outbox_claim_state'),
    sa.CheckConstraint("label IN ('AssistantOriginal', 'AssistantPruned', 'Chunk', 'Community', 'Conversation', 'Dialogue', 'ExtractedEntity', 'MemorySummary', 'Perceptual', 'SceneSummary', 'Statement', 'UserSource')", name='ck_memory_outbox_label'),
    sa.CheckConstraint("operation IN ('upsert', 'delete', 'draft_delete')", name='ck_memory_outbox_operation'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'processed', 'failed')", name='ck_memory_outbox_status'),
    sa.CheckConstraint('attempt_count BETWEEN 0 AND 3', name='ck_memory_outbox_attempt_count'),
    sa.CheckConstraint('length(label) > 0 AND length(node_id) > 0', name='ck_memory_outbox_node_identity'),
    sa.PrimaryKeyConstraint('id', name='pk_memory_storage_outbox_events'),
    sa.UniqueConstraint('sequence', name='uq_memory_outbox_sequence')
    )
    op.create_index('ix_memory_outbox_failed_cleanup', 'memory_storage_outbox_events', ['failed_at'], unique=False, postgresql_where=sa.text("status = 'failed'"))
    op.create_index('ix_memory_outbox_heartbeat', 'memory_storage_outbox_events', ['heartbeat_at'], unique=False, postgresql_where=sa.text("status = 'processing'"))
    op.create_index('ix_memory_outbox_node', 'memory_storage_outbox_events', ['label', 'node_id', 'sequence'], unique=False)
    op.create_index('ix_memory_outbox_pending', 'memory_storage_outbox_events', ['sequence'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('ix_memory_outbox_processed_cleanup', 'memory_storage_outbox_events', ['processed_at'], unique=False, postgresql_where=sa.text("status = 'processed'"))
    op.create_index('uq_memory_outbox_processing_node', 'memory_storage_outbox_events', ['label', 'node_id'], unique=True, postgresql_where=sa.text("status = 'processing'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_memory_outbox_processing_node', table_name='memory_storage_outbox_events', postgresql_where=sa.text("status = 'processing'"))
    op.drop_index('ix_memory_outbox_processed_cleanup', table_name='memory_storage_outbox_events', postgresql_where=sa.text("status = 'processed'"))
    op.drop_index('ix_memory_outbox_pending', table_name='memory_storage_outbox_events', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_memory_outbox_node', table_name='memory_storage_outbox_events')
    op.drop_index('ix_memory_outbox_heartbeat', table_name='memory_storage_outbox_events', postgresql_where=sa.text("status = 'processing'"))
    op.drop_index('ix_memory_outbox_failed_cleanup', table_name='memory_storage_outbox_events', postgresql_where=sa.text("status = 'failed'"))
    op.drop_table('memory_storage_outbox_events')
    # ### end Alembic commands ###
