"""202606291100

Revision ID: 0272a3acf6f6
Revises: f91c935a4776
Create Date: 2026-06-29 11:03:47.610925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0272a3acf6f6'
down_revision: Union[str, None] = 'f91c935a4776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_feedbacks', sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False, comment='是否收藏'))
    op.alter_column('message_feedbacks', 'feedback_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='反馈类型: like/dislike；仅收藏行为 NULL',
               existing_comment='反馈类型: like/dislike')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_feedbacks', 'feedback_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='反馈类型: like/dislike',
               existing_comment='反馈类型: like/dislike；仅收藏行为 NULL')
    op.drop_column('message_feedbacks', 'is_favorite')
    # ### end Alembic commands ###
