"""202607311744

Revision ID: 0318b3a81979
Revises: 038bd8a9bab7
Create Date: 2026-07-31 09:45:13.311143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0318b3a81979'
down_revision: Union[str, None] = '038bd8a9bab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_display_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('end_user_id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=16), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('search_mode', sa.String(length=16), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['end_user_id'], ['end_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('end_user_id', 'operation_id', 'operation', 'memory_id', name='uq_memory_display_records_user_op_memory')
    )
    op.create_table('memory_engine_display_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('end_user_id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('engine_type', sa.String(length=32), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['end_user_id'], ['end_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('end_user_id', 'engine_type', 'operation_id', name='uq_engine_display_user_type_op')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory_engine_display_records')
    op.drop_table('memory_display_records')
    # ### end Alembic commands ###
