"""202609211820

Revision ID: 0a382e59c2a0
Revises: 5a7336d91b89
Create Date: 2026-09-21 10:21:01.045044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a382e59c2a0'
down_revision: Union[str, None] = '5a7336d91b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_BACKFILL_SQL = """
UPDATE __TABLE__ SET
    input_modalities = ARRAY['text']::varchar[]
        || CASE WHEN 'vision' = ANY(capability) THEN ARRAY['image']::varchar[] ELSE '{}'::varchar[] END
        || CASE WHEN 'audio' = ANY(capability) THEN ARRAY['audio']::varchar[] ELSE '{}'::varchar[] END
        || CASE WHEN 'video' = ANY(capability) THEN ARRAY['video']::varchar[] ELSE '{}'::varchar[] END,
    output_modalities = CASE
        WHEN is_omni AND provider = 'dashscope' THEN ARRAY['text', 'audio']::varchar[]
        WHEN type IN ('image', 'video') THEN ARRAY[type]::varchar[]
        ELSE ARRAY['text']::varchar[]
    END,
    features = ARRAY(
        SELECT t.f
        FROM unnest(ARRAY['thinking', 'thinking_only', 'json_output', 'function_call']::varchar[])
             WITH ORDINALITY AS t(f, ord)
        WHERE t.f = ANY(capability)
        ORDER BY t.ord
    )
WHERE input_modalities = '{}'::varchar[]
"""

_TABLES = ("model_configs", "model_bases")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table in _TABLES:
        op.add_column(table, sa.Column(
            "input_modalities", postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'::varchar[]"), nullable=False,
            comment="输入模态（如['text','image','audio','video']）",
        ))
        op.add_column(table, sa.Column(
            "output_modalities", postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'::varchar[]"), nullable=False,
            comment="输出模态（如['text','image','audio']）",
        ))
        op.add_column(table, sa.Column(
            "features", postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'::varchar[]"), nullable=False,
            comment="能力特征（如['thinking','json_output','function_call']）",
        ))
    op.alter_column("model_configs", "is_composite", server_default=sa.text("false"))

    for table in _TABLES:
        op.execute(_BACKFILL_SQL.replace("__TABLE__", table))
        op.execute(f"UPDATE {table} SET type = 'llm' WHERE type = 'chat'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 不回退 type：'llm' 在旧代码中合法，且无法区原本 chat 的行；回滚安全性由读口归一保证
    op.alter_column("model_configs", "is_composite", server_default=sa.text("true"))
    for table in _TABLES:
        op.drop_column(table, "features")
        op.drop_column(table, "output_modalities")
        op.drop_column(table, "input_modalities")
    # ### end Alembic commands ###
