"""202607241755

Revision ID: 0cbae4a19048
Revises: f33568f8aa8f
Create Date: 2026-07-24 09:55:33.816593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cbae4a19048'
down_revision: Union[str, None] = 'f33568f8aa8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_conversations_user_updated', 'conversations', ['user_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_conversations_user_updated', table_name='conversations')
    # ### end Alembic commands ###
