"""202608131333

Revision ID: 0ce6da8e1ab3
Revises: dae70859b388
Create Date: 2026-08-13 05:35:11.437247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce6da8e1ab3'
down_revision: Union[str, None] = 'dae70859b388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memory_messages', 'original_message_id',
               existing_type=sa.UUID(),
               comment='原始消息 ID（对 messages 表的逻辑引用，非外键；工作流/API/MCP 消息为 NULL）',
               existing_comment='原始消息 ID（对 messages 表的引用；工作流/API/MCP 消息为 NULL）',
               existing_nullable=True)
    op.drop_constraint(op.f('memory_messages_original_message_id_fkey'), 'memory_messages', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('memory_messages_original_message_id_fkey'), 'memory_messages', 'messages', ['original_message_id'], ['id'])
    op.alter_column('memory_messages', 'original_message_id',
               existing_type=sa.UUID(),
               comment='原始消息 ID（对 messages 表的引用；工作流/API/MCP 消息为 NULL）',
               existing_comment='原始消息 ID（对 messages 表的逻辑引用，非外键；工作流/API/MCP 消息为 NULL）',
               existing_nullable=True)
    # ### end Alembic commands ###
