"""202609091626

Revision ID: 11172ee5d4fd
Revises: cd1237005723
Create Date: 2026-09-09 08:27:17.605058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11172ee5d4fd'
down_revision: Union[str, None] = 'cd1237005723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_config', sa.Column('scene_threshold', sa.Float(), server_default='0.8', nullable=False, comment='Scene 连续性阈值'))
    op.add_column('memory_config', sa.Column('scene_history_window_size', sa.Integer(), server_default='4', nullable=False, comment='BERT 历史 user 窗口'))
    op.add_column('memory_config', sa.Column('scene_min_turns', sa.Integer(), server_default='2', nullable=False, comment='Scene 最小保护轮次'))
    op.add_column('memory_config', sa.Column('scene_max_turns', sa.Integer(), server_default='10', nullable=False, comment='Scene 最大轮次'))
    op.add_column('memory_config', sa.Column('scene_idle_timeout_seconds', sa.Integer(), server_default='86400', nullable=False, comment='Scene 静默超时秒数'))
    op.add_column('memory_config', sa.Column('scene_min_chars_to_summary', sa.Integer(), server_default='0', nullable=False, comment='SceneSummary 最小有效字符数'))
    op.add_column('memory_config', sa.Column('time_decay_penalty', sa.Float(), server_default='0.1', nullable=False, comment='时间衰减惩罚（0-0.2），仅存储，暂不参与计算'))
    op.add_column('memory_messages', sa.Column('scene_boundary', sa.String(length=32), nullable=True, comment='场景判断：CONTINUE/SHIFTED/BERT_FAILED_CONTINUE；NULL=不适用或尚未写入'))
    op.add_column('memory_messages', sa.Column('scene_summary_claimed_at', sa.DateTime(), nullable=True, comment='SceneSummary 首次被领取时间；非空表示已派发或处理中，不保证生成成功'))
    op.create_index('idx_memory_messages_scene_conversation_order', 'memory_messages', ['end_user_id', 'conversation_id', 'created_at', 'message_seq', 'id'], unique=False, postgresql_where=sa.text("conversation_id IS NOT NULL AND should_memorize = TRUE AND role IN ('user', 'assistant')"))
    op.create_index('idx_memory_messages_scene_shifted_conversation', 'memory_messages', ['end_user_id', 'conversation_id', 'created_at', 'id'], unique=False, postgresql_where=sa.text("conversation_id IS NOT NULL AND role = 'user' AND should_memorize = TRUE AND scene_boundary = 'SHIFTED'"))
    op.create_index('idx_memory_messages_scene_shifted_source', 'memory_messages', ['end_user_id', 'source', 'created_at', 'id'], unique=False, postgresql_where=sa.text("conversation_id IS NULL AND role = 'user' AND should_memorize = TRUE AND scene_boundary = 'SHIFTED'"))
    op.create_index('idx_memory_messages_scene_source_order', 'memory_messages', ['end_user_id', 'source', 'created_at', 'message_seq', 'id'], unique=False, postgresql_where=sa.text("conversation_id IS NULL AND should_memorize = TRUE AND role IN ('user', 'assistant')"))
    op.create_index('idx_memory_messages_scene_unclaimed_scan', 'memory_messages', ['created_at', 'id'], unique=False, postgresql_where=sa.text("role = 'user' AND should_memorize = TRUE AND scene_boundary = 'SHIFTED' AND scene_summary_claimed_at IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_memory_messages_scene_unclaimed_scan', table_name='memory_messages', postgresql_where=sa.text("role = 'user' AND should_memorize = TRUE AND scene_boundary = 'SHIFTED' AND scene_summary_claimed_at IS NULL"))
    op.drop_index('idx_memory_messages_scene_source_order', table_name='memory_messages', postgresql_where=sa.text("conversation_id IS NULL AND should_memorize = TRUE AND role IN ('user', 'assistant')"))
    op.drop_index('idx_memory_messages_scene_shifted_source', table_name='memory_messages', postgresql_where=sa.text("conversation_id IS NULL AND role = 'user' AND should_memorize = TRUE AND scene_boundary = 'SHIFTED'"))
    op.drop_index('idx_memory_messages_scene_shifted_conversation', table_name='memory_messages', postgresql_where=sa.text("conversation_id IS NOT NULL AND role = 'user' AND should_memorize = TRUE AND scene_boundary = 'SHIFTED'"))
    op.drop_index('idx_memory_messages_scene_conversation_order', table_name='memory_messages', postgresql_where=sa.text("conversation_id IS NOT NULL AND should_memorize = TRUE AND role IN ('user', 'assistant')"))
    op.drop_column('memory_messages', 'scene_summary_claimed_at')
    op.drop_column('memory_messages', 'scene_boundary')
    op.drop_column('memory_config', 'time_decay_penalty')
    op.drop_column('memory_config', 'scene_min_chars_to_summary')
    op.drop_column('memory_config', 'scene_idle_timeout_seconds')
    op.drop_column('memory_config', 'scene_max_turns')
    op.drop_column('memory_config', 'scene_min_turns')
    op.drop_column('memory_config', 'scene_history_window_size')
    op.drop_column('memory_config', 'scene_threshold')
    # ### end Alembic commands ###
