"""202610081427

Revision ID: 13040b4dfa6e
Revises: 40ceae7eb6f3
Create Date: 2026-10-08 06:28:51.035754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13040b4dfa6e'
down_revision: Union[str, None] = '40ceae7eb6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_reembed_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('old_embedding_config_id', sa.String(), nullable=True),
    sa.Column('new_embedding_config_id', sa.String(), nullable=False),
    sa.Column('old_model_name', sa.String(), nullable=True),
    sa.Column('new_model_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('total_end_users', sa.Integer(), server_default='0', nullable=False),
    sa.Column('processed_end_users', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_nodes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('processed_nodes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('failed_nodes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed')", name='ck_memory_reembed_jobs_status'),
    sa.CheckConstraint('processed_end_users <= total_end_users', name='ck_memory_reembed_jobs_end_user_progress'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memory_reembed_jobs_active', 'memory_reembed_jobs', ['workspace_id'], unique=False, postgresql_where="status IN ('pending', 'running')")
    op.create_index(op.f('ix_memory_reembed_jobs_id'), 'memory_reembed_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_memory_reembed_jobs_status'), 'memory_reembed_jobs', ['status'], unique=False)
    op.create_index('ix_memory_reembed_jobs_workspace_created', 'memory_reembed_jobs', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_memory_reembed_jobs_workspace_id'), 'memory_reembed_jobs', ['workspace_id'], unique=False)
    op.create_table('memory_reembed_job_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('end_user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_nodes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('processed_nodes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_nodes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'done', 'failed')", name='ck_memory_reembed_job_users_status'),
    sa.CheckConstraint('attempts >= 0', name='ck_memory_reembed_job_users_attempts'),
    sa.ForeignKeyConstraint(['job_id'], ['memory_reembed_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'end_user_id', name='uq_memory_reembed_job_users_scope')
    )
    op.create_index('ix_memory_reembed_job_users_pending', 'memory_reembed_job_users', ['job_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memory_reembed_job_users_pending', table_name='memory_reembed_job_users')
    op.drop_table('memory_reembed_job_users')
    op.drop_index(op.f('ix_memory_reembed_jobs_workspace_id'), table_name='memory_reembed_jobs')
    op.drop_index('ix_memory_reembed_jobs_workspace_created', table_name='memory_reembed_jobs')
    op.drop_index(op.f('ix_memory_reembed_jobs_status'), table_name='memory_reembed_jobs')
    op.drop_index(op.f('ix_memory_reembed_jobs_id'), table_name='memory_reembed_jobs')
    op.drop_index('ix_memory_reembed_jobs_active', table_name='memory_reembed_jobs', postgresql_where="status IN ('pending', 'running')")
    op.drop_table('memory_reembed_jobs')
    # ### end Alembic commands ###
