"""202610101219

Revision ID: 14e152c311c1
Revises: d04672399454
Create Date: 2026-10-10 04:33:21.572553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14e152c311c1'
down_revision: Union[str, None] = 'd04672399454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("UPDATE workspaces SET storage_type = 'neo4j' WHERE storage_type IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_executions', 'orchestration_mode',
               existing_type=sa.VARCHAR(length=20),
               comment='编排模式: supervisor（主管三段式）| supervisor_loop（主管 ReAct 循环）| collaboration（协作）；非集群执行时为 NULL',
               existing_comment='编排模式: supervisor（主管）| collaboration（协作）；非集群执行时为 NULL',
               existing_nullable=True)
    op.add_column('multi_agent_configs', sa.Column('supervisor_config', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment="主管配置（全模式；supervisor_loop 下还含主管本体能力面）: {'system_prompt': str, 'web_search': bool, 'memory': {'enabled': bool}, 'knowledge_retrieval': {...}, 'tools': [...], 'skills': {...}, 'variables': [{'name', 'display_name', 'type', 'required', 'default_value', ...}]}"))
    op.alter_column('multi_agent_configs', 'orchestration_mode',
               existing_type=sa.VARCHAR(length=20),
               comment='协作模式: collaboration（协作）| supervisor（主管三段式）| supervisor_loop（主管 ReAct 循环，默认）',
               existing_comment='协作模式: collaboration（协作）| supervisor（监督）',
               existing_nullable=False)
    op.alter_column('workspaces', 'storage_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'storage_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('multi_agent_configs', 'orchestration_mode',
               existing_type=sa.VARCHAR(length=20),
               comment='协作模式: collaboration（协作）| supervisor（监督）',
               existing_comment='协作模式: collaboration（协作）| supervisor（主管三段式）| supervisor_loop（主管 ReAct 循环，默认）',
               existing_nullable=False)
    op.drop_column('multi_agent_configs', 'supervisor_config')
    op.alter_column('agent_executions', 'orchestration_mode',
               existing_type=sa.VARCHAR(length=20),
               comment='编排模式: supervisor（主管）| collaboration（协作）；非集群执行时为 NULL',
               existing_comment='编排模式: supervisor（主管三段式）| supervisor_loop（主管 ReAct 循环）| collaboration（协作）；非集群执行时为 NULL',
               existing_nullable=True)
    # ### end Alembic commands ###
