"""202605182022

Revision ID: 1620abe078cf
Revises: 83ba712a9a53
Create Date: 2026-05-18 20:23:02.599739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1620abe078cf'
down_revision: Union[str, None] = '83ba712a9a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_reflection_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('end_user_id', sa.UUID(), nullable=False),
    sa.Column('sub_problem', sa.String(length=32), nullable=False),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('baseline', sa.String(length=16), nullable=True),
    sa.Column('strategy', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary_text', sa.String(length=256), nullable=True),
    sa.Column('entity_ids', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('statement_ids', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('trigger_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('solution_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_reflection_log_end_user_id'), 'memory_reflection_log', ['end_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_reflection_log_end_user_id'), table_name='memory_reflection_log')
    op.drop_table('memory_reflection_log')
    # ### end Alembic commands ###
