"""202603252115

Revision ID: 1ea8fe97b5b7
Revises: e28bcc212da5
Create Date: 2026-03-25 21:14:41.825048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea8fe97b5b7'
down_revision: Union[str, None] = 'e28bcc212da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('contact_name', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('contact_phone', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('plan', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('plan_expired_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('api_ops_rate_limit', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'status')
    op.drop_column('tenants', 'api_ops_rate_limit')
    op.drop_column('tenants', 'plan_expired_at')
    op.drop_column('tenants', 'plan')
    op.drop_column('tenants', 'contact_phone')
    op.drop_column('tenants', 'contact_email')
    op.drop_column('tenants', 'contact_name')
    # ### end Alembic commands ###
