"""20260116

Revision ID: 1fd7d0e703b3
Revises: 9ab9b6393f32
Create Date: 2026-01-16 13:17:37.060026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd7d0e703b3'
down_revision: Union[str, None] = '9ab9b6393f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion_suggestions_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('end_user_id', sa.String(length=255), nullable=False, comment='终端用户ID（组ID）'),
    sa.Column('health_summary', sa.Text(), nullable=False, comment='健康状态摘要'),
    sa.Column('suggestions', sa.JSON(), nullable=False, comment='建议列表（JSON格式）'),
    sa.Column('generated_at', sa.DateTime(), nullable=False, comment='生成时间'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotion_suggestions_cache_end_user_id'), 'emotion_suggestions_cache', ['end_user_id'], unique=True)
    op.create_index(op.f('ix_emotion_suggestions_cache_id'), 'emotion_suggestions_cache', ['id'], unique=False)
    op.create_table('implicit_memory_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('end_user_id', sa.String(length=255), nullable=False, comment='终端用户ID'),
    sa.Column('preferences', sa.JSON(), nullable=False, comment='偏好标签列表（JSON格式）'),
    sa.Column('portrait', sa.JSON(), nullable=False, comment='四维画像对象（JSON格式）'),
    sa.Column('interest_areas', sa.JSON(), nullable=False, comment='兴趣领域分布对象（JSON格式）'),
    sa.Column('habits', sa.JSON(), nullable=False, comment='行为习惯列表（JSON格式）'),
    sa.Column('generated_at', sa.DateTime(), nullable=False, comment='生成时间'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_implicit_memory_cache_end_user_id'), 'implicit_memory_cache', ['end_user_id'], unique=True)
    op.create_index(op.f('ix_implicit_memory_cache_id'), 'implicit_memory_cache', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_implicit_memory_cache_id'), table_name='implicit_memory_cache')
    op.drop_index(op.f('ix_implicit_memory_cache_end_user_id'), table_name='implicit_memory_cache')
    op.drop_table('implicit_memory_cache')
    op.drop_index(op.f('ix_emotion_suggestions_cache_id'), table_name='emotion_suggestions_cache')
    op.drop_index(op.f('ix_emotion_suggestions_cache_end_user_id'), table_name='emotion_suggestions_cache')
    op.drop_table('emotion_suggestions_cache')
    # ### end Alembic commands ###
