"""202609211914

Revision ID: 24eb21498a55
Revises: 490a79194008
Create Date: 2026-09-21 11:15:36.072737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24eb21498a55'
down_revision: Union[str, None] = '490a79194008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_TABLE = "memory_storage_outbox_events"
_CONSTRAINT = "ck_memory_outbox_label"
_LABEL_CHECK = (
    "label IN ('AssistantOriginal', 'AssistantPruned', 'Chunk', "
    "'Community', 'Conversation', 'Dialogue', 'ExtractedEntity', "
    "'MemorySummary', 'Perceptual', 'Preference', 'SceneSummary', "
    "'Statement', 'UserSource')"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(_CONSTRAINT, _TABLE, type_="check")
    op.add_column('memory_config', sa.Column('preference_engine_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否启用 Coding Agent 偏好处理器'))
    op.add_column('memory_config', sa.Column('preference_custom_keywords', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='用户自定义偏好门禁关键词'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(_CONSTRAINT, _TABLE, _LABEL_CHECK)
    op.drop_column('memory_config', 'preference_custom_keywords')
    op.drop_column('memory_config', 'preference_engine_enabled')
    # ### end Alembic commands ###
