"""202608271533

Revision ID: 2688cd7291ec
Revises: 0ce6da8e1ab3
Create Date: 2026-08-27 07:47:12.146642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2688cd7291ec'
down_revision: Union[str, None] = '0ce6da8e1ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('end_users', sa.Column('channel_source', sa.String(), nullable=True, comment='渠道来源（如 api / mcp / workflow / web 等）'))
    op.add_column('end_users', sa.Column('identity_features', sa.String(), nullable=True, comment='跨渠道身份标识（单个标识，带标识=长时，不带=临时）'))
    op.add_column('end_users', sa.Column('identity_status', sa.String(), server_default='temporary', nullable=False, comment='身份状态: temporary / confirmed / expired'))
    op.create_index('idx_end_users_ws_identity', 'end_users', ['workspace_id', 'identity_features'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index('ix_end_users_workspace_write_time', 'end_users', ['workspace_id', 'write_time'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_end_users_workspace_write_time', table_name='end_users', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_index('idx_end_users_ws_identity', table_name='end_users', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_column('end_users', 'identity_status')
    op.drop_column('end_users', 'identity_features')
    op.drop_column('end_users', 'channel_source')
    # ### end Alembic commands ###
