"""202608061900

Revision ID: 2a50ba49c523
Revises: 91a12ce4387d
Create Date: 2026-08-06 19:00:33.260008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a50ba49c523'
down_revision: Union[str, None] = '91a12ce4387d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_role', sa.String(length=32), server_default='source', nullable=False, comment='source or derived_image'))
    op.add_column('files', sa.Column('source_document_id', sa.UUID(), nullable=True, comment='documents.id for a derived image asset'))
    op.create_index(op.f('ix_files_file_role'), 'files', ['file_role'], unique=False)
    op.create_index(op.f('ix_files_source_document_id'), 'files', ['source_document_id'], unique=False)
    op.add_column('memory_display_records', sa.Column('query', sa.Text(), nullable=True))
    op.alter_column('memory_display_records', 'memory_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('memory_display_records', 'memory_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('memory_display_records', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index('idx_memory_display_retrieve_user_occurred', 'memory_display_records', ['end_user_id', sa.literal_column('occurred_at DESC'), sa.literal_column('id DESC')], unique=False, postgresql_where=sa.text("operation = 'RETRIEVE'"))
    op.create_index('uq_memory_display_retrieve_user_operation', 'memory_display_records', ['end_user_id', 'operation_id'], unique=True, postgresql_where=sa.text("operation = 'RETRIEVE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_memory_display_retrieve_user_operation', table_name='memory_display_records', postgresql_where=sa.text("operation = 'RETRIEVE'"))
    op.drop_index('idx_memory_display_retrieve_user_occurred', table_name='memory_display_records', postgresql_where=sa.text("operation = 'RETRIEVE'"))
    op.alter_column('memory_display_records', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('memory_display_records', 'memory_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('memory_display_records', 'memory_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('memory_display_records', 'query')
    op.drop_index(op.f('ix_files_source_document_id'), table_name='files')
    op.drop_index(op.f('ix_files_file_role'), table_name='files')
    op.drop_column('files', 'source_document_id')
    op.drop_column('files', 'file_role')
    # ### end Alembic commands ###
