"""202606051911

Revision ID: 340a8c49e58b
Revises: 7335e9b0e781
Create Date: 2026-06-05 19:12:15.294671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340a8c49e58b'
down_revision: Union[str, None] = '7335e9b0e781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_node_executions', sa.Column('app_id', sa.UUID(), nullable=False))
    op.add_column('workflow_node_executions', sa.Column('workflow_config_id', sa.UUID(), nullable=False))
    op.alter_column('workflow_node_executions', 'execution_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_workflow_node_executions_app_id'), 'workflow_node_executions', ['app_id'], unique=False)
    op.create_index(op.f('ix_workflow_node_executions_workflow_config_id'), 'workflow_node_executions', ['workflow_config_id'], unique=False)
    op.create_foreign_key('fk_workflow_node_executions_workflow_config_id', 'workflow_node_executions', 'workflow_configs', ['workflow_config_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_workflow_node_executions_app_id', 'workflow_node_executions', 'apps', ['app_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
    op.execute(
        """
        UPDATE workflow_node_executions AS wne
        SET
            app_id = we.app_id,
            workflow_config_id = we.workflow_config_id
        FROM workflow_executions AS we
        WHERE wne.execution_id = we.id
        """
    )

    op.alter_column("workflow_node_executions", "app_id", nullable=False)
    op.alter_column("workflow_node_executions", "workflow_config_id", nullable=False)
    op.alter_column("workflow_node_executions", "execution_id", nullable=True)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_workflow_node_executions_app_id', 'workflow_node_executions', type_='foreignkey')
    op.drop_constraint('fk_workflow_node_executions_workflow_config_id', 'workflow_node_executions', type_='foreignkey')
    op.drop_index(op.f('ix_workflow_node_executions_workflow_config_id'), table_name='workflow_node_executions')
    op.drop_index(op.f('ix_workflow_node_executions_app_id'), table_name='workflow_node_executions')
    op.alter_column('workflow_node_executions', 'execution_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('workflow_node_executions', 'workflow_config_id')
    op.drop_column('workflow_node_executions', 'app_id')
    # ### end Alembic commands ###
