"""202607021019

Revision ID: 40169b944545
Revises: 51148484b8b5
Create Date: 2026-07-02 02:19:47.344565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40169b944545'
down_revision: Union[str, None] = '51148484b8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('vision', sa.String(), nullable=True))
    op.add_column('workspaces', sa.Column('audio', sa.String(), nullable=True))
    op.add_column('workspaces', sa.Column('video', sa.String(), nullable=True))
    op.add_column('workspaces', sa.Column('is_default_config', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'is_default_config')
    op.drop_column('workspaces', 'video')
    op.drop_column('workspaces', 'audio')
    op.drop_column('workspaces', 'vision')
    # ### end Alembic commands ###
