"""202609241636

Revision ID: 40ceae7eb6f3
Revises: 24eb21498a55
Create Date: 2026-09-24 16:38:10.890935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ceae7eb6f3'
down_revision: Union[str, None] = '24eb21498a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_end_users_ws_active_id', 'end_users', ['workspace_id', 'id'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_end_users_ws_active_id', table_name='end_users', postgresql_where=sa.text('is_active = TRUE'))
    # ### end Alembic commands ###
