"""202609211837

Revision ID: 490a79194008
Revises: 0a382e59c2a0
Create Date: 2026-09-21 10:38:05.571455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '490a79194008'
down_revision: Union[str, None] = '0a382e59c2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE memory_config
        SET chunker_strategy = 'RecursiveChunker',
            updated_at = timezone('UTC', now())
        WHERE chunker_strategy IN (
            'SemanticChunker',
            'LateChunker',
            'NeuralChunker',
            'HybridChunker'
        )
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
