"""202605151650

Revision ID: 4eb827a38506
Revises: 37e2a73b28c4
Create Date: 2026-05-15 17:06:37.186555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4eb827a38506'
down_revision: Union[str, None] = '37e2a73b28c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True, comment='关联的 assistant 消息 ID'),
    sa.Column('agent_config_id', sa.UUID(), nullable=True, comment='执行时使用的 Agent 配置 ID'),
    sa.Column('release_id', sa.UUID(), nullable=True, comment='执行时使用的发布版本 ID（试运行时为 NULL）'),
    sa.Column('triggered_by', sa.UUID(), nullable=True, comment='触发执行的用户 ID'),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('elapsed_time', sa.Float(), nullable=True, comment='总耗时（秒）'),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展元数据'),
    sa.ForeignKeyConstraint(['agent_config_id'], ['agent_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['release_id'], ['app_releases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_executions_agent_config_id'), 'agent_executions', ['agent_config_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_app_id'), 'agent_executions', ['app_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_conversation_id'), 'agent_executions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_id'), 'agent_executions', ['id'], unique=False)
    op.create_index(op.f('ix_agent_executions_message_id'), 'agent_executions', ['message_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_release_id'), 'agent_executions', ['release_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_status'), 'agent_executions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_executions_triggered_by'), 'agent_executions', ['triggered_by'], unique=False)
    op.add_column('knowledges', sa.Column('external_id', sa.String(length=36), nullable=True, comment='user-defined external identifier, workspace-unique'))
    op.create_index(op.f('ix_knowledges_external_id'), 'knowledges', ['external_id'], unique=False)
    op.add_column('messages', sa.Column('status', sa.String(length=20), server_default='completed', nullable=False, comment='消息状态: completed/failed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'status')
    op.drop_index(op.f('ix_knowledges_external_id'), table_name='knowledges')
    op.drop_column('knowledges', 'external_id')
    op.drop_index(op.f('ix_agent_executions_triggered_by'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_status'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_release_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_message_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_conversation_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_app_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_config_id'), table_name='agent_executions')
    op.drop_table('agent_executions')
    # ### end Alembic commands ###
