"""202609132037

Revision ID: 511076b5c2e2
Revises: bf8b73e3f1ef
Create Date: 2026-09-13 12:39:00.210207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '511076b5c2e2'
down_revision: Union[str, None] = 'bf8b73e3f1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_usage_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('source_service', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('capability', sa.String(length=32), nullable=False),
    sa.Column('stream', sa.Boolean(), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('images_count', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_model_usage_records_event_id')
    )
    op.create_index('ix_usage_channel_time', 'model_usage_records', ['channel_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_usage_model_time', 'model_usage_records', ['provider', 'model_name', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_usage_resource_time', 'model_usage_records', ['tenant_id', 'resource_type', 'resource_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_usage_tenant_time', 'model_usage_records', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('model_channels',
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='凭据归属租户'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='供应商（不允许 composite）'),
    sa.Column('model_names', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='覆盖模型集；[]=provider 级默认渠道'),
    sa.Column('api_base', sa.String(length=512), nullable=True, comment='执行端点；空=provider 默认 base_url（不参与覆盖匹配）'),
    sa.Column('credential_encrypted', sa.Text(), nullable=False, comment='信封 v{ver}:iv:tag:ct'),
    sa.Column('credential_sha256', sa.String(length=64), nullable=False, comment='凭据指纹（幂等合并键）'),
    sa.Column('credential_masked', sa.String(length=255), nullable=False, comment='展示用掩码 sk-****abcd'),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False, comment='同精确度主备权重'),
    sa.Column('cooldown_until_ms', sa.BigInteger(), nullable=True, comment='熔断预留（阶段一恒空）'),
    sa.Column('source', sa.String(length=20), server_default='manual', nullable=False, comment='manual|platform'),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='speedbear 等企业语义'),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='登记人弱引用（不建 FK）'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'tenant_id', 'api_base', 'credential_sha256', name='uq_channel_credential', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_channel_tenant_provider', 'model_channels', ['tenant_id', 'provider'], unique=False)
    op.create_index(op.f('ix_model_channels_id'), 'model_channels', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_channels_id'), table_name='model_channels')
    op.drop_index('ix_channel_tenant_provider', table_name='model_channels')
    op.drop_table('model_channels')
    op.drop_index('ix_usage_tenant_time', table_name='model_usage_records')
    op.drop_index('ix_usage_resource_time', table_name='model_usage_records')
    op.drop_index('ix_usage_model_time', table_name='model_usage_records')
    op.drop_index('ix_usage_channel_time', table_name='model_usage_records')
    op.drop_table('model_usage_records')
    # ### end Alembic commands ###
