"""202606301752

Revision ID: 51148484b8b5
Revises: 0272a3acf6f6
Create Date: 2026-06-30 17:52:35.828874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51148484b8b5'
down_revision: Union[str, None] = '0272a3acf6f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('memory_config', sa.UUID(), nullable=True))
    op.execute("""
        UPDATE workspaces
        SET memory_config = (
            SELECT config_id
            FROM memory_config
            WHERE memory_config.workspace_id = workspaces.id
              AND is_default = true
            LIMIT 1
        )
    """)

    op.execute("""
        WITH new_configs AS (
            INSERT INTO memory_config (
                config_id, config_name, workspace_id,
                llm_id, embedding_id, rerank_id,
                reflection_model_id, emotion_model_id,
                is_default, state,
                chunker_strategy,
                enable_llm_dedup_blockwise, enable_llm_disambiguation, deep_retrieval,
                t_type_strict, t_name_strict, t_overall,
                pruning_enabled, pruning_scene, pruning_threshold,
                enable_self_reflexion, iteration_period, reflexion_range, baseline,
                memory_verify, quality_assessment,
                statement_granularity, include_dialogue_context, max_context,
                lambda_time, lambda_mem, "offset",
                decay_constant, forgetting_threshold, forgetting_interval_hours,
                enable_llm_summary, max_merge_batch_size, max_history_length, min_days_since_access,
                emotion_enabled, emotion_extract_keywords, emotion_min_intensity, emotion_enable_subject,
                created_at, updated_at
            )
            SELECT
                gen_random_uuid(),
                COALESCE(w.name, 'workspace') || ' 默认配置',
                w.id,
                w.llm, w.embedding, w.rerank,
                w.llm, w.llm,
                true, false,
                'RecursiveChunker',
                true, true, true,
                0.8, 0.8, 0.8,
                true, NULL, NULL,
                true, '3', 'partial', 'TIME',
                true, true,
                2, false, 1000,
                0.5, 0.5, 0.0,
                0.5, 0.3, 24,
                true, 100, 100, 30,
                true, true, 0.1, true,
                timezone('UTC', now()), timezone('UTC', now())
            FROM workspaces w
            WHERE w.memory_config IS NULL
            RETURNING config_id, workspace_id
        )
        UPDATE workspaces
        SET memory_config = nc.config_id
        FROM new_configs nc
        WHERE workspaces.id = nc.workspace_id
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'memory_config')
    # ### end Alembic commands ###
