"""202607031708

Revision ID: 5211ceecdea4
Revises: 40169b944545
Create Date: 2026-07-03 09:09:20.089361

变更内容（对应 api/docs/v0.3.11/2-设计文档-评审.md）：
1. memory_messages 新增 end_user_id（VARCHAR, NOT NULL）、source 字段
2. memory_messages.conversation_id 改为 nullable（API/MCP 写入不再建 conversation）
3. 新增 (end_user_id, source) 复合索引
4. 回填历史 source：
   - conversation.app_id = SENTINEL → 'service_api'（历史 API/MCP 写入均走哨兵会话）
   - apps.type = workflow/pure_workflow → 'workflow'
   - apps.type = agent/multi_agent（非 SENTINEL）→ 'agent'
   - 孤儿消息（无法关联到 conversation/app）→ 'service_api'
5. 回填历史 end_user_id：沿 conversation_id → conversations.user_id 取值
   回填后若仍有残留 NULL（conversation.user_id 为空），中止迁移交由运维清理
6. 软删除历史哨兵 conversation（is_active=FALSE）+ 哨兵 App（is_active=FALSE）

注意：
- 哨兵 App 行（apps 表）保留但置 is_active=FALSE，不做物理删除（conversations.app_id FK 仍引用）。
- content_search / conversation_repository 中的 app_id != SENTINEL 过滤本次保留不动。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5211ceecdea4'
down_revision: Union[str, None] = '40169b944545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SENTINEL_APP_ID = '00000000-0000-0000-0000-000000000001'

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_default_model_presets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('singleton_key', sa.String(), nullable=False),
    sa.Column('llm_model_config_id', sa.UUID(), nullable=False),
    sa.Column('embedding_model_config_id', sa.UUID(), nullable=False),
    sa.Column('rerank_model_config_id', sa.UUID(), nullable=False),
    sa.Column('vision_model_config_id', sa.UUID(), nullable=False),
    sa.Column('audio_model_config_id', sa.UUID(), nullable=False),
    sa.Column('video_model_config_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audio_model_config_id'], ['model_configs.id'], ),
    sa.ForeignKeyConstraint(['embedding_model_config_id'], ['model_configs.id'], ),
    sa.ForeignKeyConstraint(['llm_model_config_id'], ['model_configs.id'], ),
    sa.ForeignKeyConstraint(['rerank_model_config_id'], ['model_configs.id'], ),
    sa.ForeignKeyConstraint(['video_model_config_id'], ['model_configs.id'], ),
    sa.ForeignKeyConstraint(['vision_model_config_id'], ['model_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('singleton_key')
    )
    op.create_index(op.f('ix_workspace_default_model_presets_id'), 'workspace_default_model_presets', ['id'], unique=False)
    bind = op.get_bind()

    # 1. memory_messages 新增字段
    #    end_user_id / source 先加为 nullable，稍后回填真实值再置 NOT NULL，
    #    避免 ADD COLUMN NOT NULL 的表重写/默认值副作用。
    op.add_column(
        'memory_messages',
        sa.Column(
            'end_user_id',
            sa.String(),
            nullable=True,
            comment='终端用户 ID（字符串，与 conversation.user_id / 各 schema 的 end_user_id 对齐）；所有写入路径必填',
        ),
    )
    op.add_column(
        'memory_messages',
        sa.Column(
            'source',
            sa.String(length=32),
            nullable=True,
            comment='写入来源：agent | service_api | mcp | workflow',
        ),
    )

    # 2. conversation_id 改为 nullable（API/MCP 写入不再建 conversation）
    op.alter_column(
        'memory_messages',
        'conversation_id',
        existing_type=postgresql.UUID(as_uuid=True),
        nullable=True,
        comment='会话 ID（agent/workflow 写入时非空；API/MCP 写入时为 NULL）',
    )

    # 3. 索引（覆盖工作记忆聚合查询 + API/MCP seq 分配）
    op.create_index(
        'idx_memory_messages_user_source',
        'memory_messages',
        ['end_user_id', 'source'],
    )

    # 4. 回填历史 source：
    #    - conversation.app_id = SENTINEL → 'service_api'（历史 API/MCP 写入都走的哨兵会话）
    #    - apps.type IN (workflow, pure_workflow) → 'workflow'
    #    - apps.type IN (agent, multi_agent) 且非 SENTINEL → 'agent'
    op.execute(sa.text(f"""
            UPDATE memory_messages mm
            SET source = CASE
                WHEN c.app_id = '{SENTINEL_APP_ID}' THEN 'service_api'
                WHEN a.type IN ('workflow', 'pure_workflow') THEN 'workflow'
                ELSE 'agent'
            END
            FROM conversations c
            JOIN apps a ON a.id = c.app_id
            WHERE mm.conversation_id = c.id
              AND mm.source IS NULL
        """))
    # 孤儿消息兜底（找不到 conversation/app 关联的行）→ 'service_api'
    op.execute(sa.text("UPDATE memory_messages SET source = 'service_api' WHERE source IS NULL"))
    op.alter_column(
        'memory_messages',
        'source',
        existing_type=sa.String(length=32),
        nullable=False,
    )

    # 5. 回填历史 end_user_id：取 conversations.user_id（字符串），类型一致直接赋值。
    op.execute(sa.text("""
            UPDATE memory_messages mm
            SET end_user_id = c.user_id
            FROM conversations c
            WHERE mm.conversation_id = c.id
              AND mm.end_user_id IS NULL
              AND c.user_id IS NOT NULL
              AND c.user_id <> ''
        """))

    # 6. 残留检查：end_user_id 置 NOT NULL 前，若仍有无法回填的行（conversation.user_id
    #    为空），中止迁移，交由运维定位清理，避免静默删数据。
    residual = bind.execute(
        sa.text("SELECT count(*) FROM memory_messages WHERE end_user_id IS NULL")
    ).scalar()
    if residual and int(residual) > 0:
        raise RuntimeError(
            f"迁移中止：memory_messages 存在 {residual} 行无法回填 end_user_id "
            f"（对应 conversation.user_id 为空）。请先清理这些行或补齐 "
            f"conversations.user_id，再重新执行迁移。"
        )

    op.alter_column(
        'memory_messages',
        'end_user_id',
        existing_type=sa.String(),
        nullable=False,
    )

    # 6. 软删除历史哨兵 conversation + 哨兵 App
    #    - conversations: 工作记忆统计天然跳过 is_active=FALSE 的会话
    #    - apps: 哨兵 App 置为不活跃，代码层的 app_id != SENTINEL 过滤仍有效
    #      （保留行而非物理删除，避免违反 conversations.app_id FK 约束）
    op.execute(sa.text(f"""
            UPDATE conversations SET is_active = FALSE
            WHERE app_id = '{SENTINEL_APP_ID}'
        """))
    op.execute(sa.text(f"""
            UPDATE apps SET is_active = FALSE
            WHERE id = '{SENTINEL_APP_ID}'
        """))
    op.add_column('workspaces', sa.Column('default_model_notice_pending', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚仅保证结构可回退，历史数据不做恢复（is_active/apps 记录不还原）。

    策略：
    - conversation_id 保持 nullable，不改回 NOT NULL。
      旧代码写入时始终携带 conversation_id，不会产生 NULL，因此 nullable 残留
      对旧逻辑无影响；同时避免因 API/MCP 写入的 NULL 行导致回滚失败。
    - 哨兵 conversation 的 is_active 不还原（已软删除的行保持 FALSE）。
    - 删除新增的 source / end_user_id 列和索引。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'default_model_notice_pending')
    op.drop_index('idx_memory_messages_user_source', table_name='memory_messages')

    # 不将 conversation_id 改回 NOT NULL —— 保留 nullable，旧代码不受影响
    op.drop_column('memory_messages', 'source')
    op.drop_column('memory_messages', 'end_user_id')
    op.drop_index(op.f('ix_workspace_default_model_presets_id'), table_name='workspace_default_model_presets')
    op.drop_table('workspace_default_model_presets')
    # ### end Alembic commands ###
