"""202609171647

Revision ID: 547effcc16ef
Revises: 511076b5c2e2
Create Date: 2026-09-17 08:48:12.606156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547effcc16ef'
down_revision: Union[str, None] = '511076b5c2e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledges', sa.Column('audio2text_id', sa.UUID(), nullable=True, comment='audio transcription model ID'))
    op.add_column('knowledges', sa.Column('video2text_id', sa.UUID(), nullable=True, comment='video understanding model ID'))
    op.create_foreign_key('knowledges_video2text_id_fkey', 'knowledges', 'model_configs', ['video2text_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('knowledges_audio2text_id_fkey', 'knowledges', 'model_configs', ['audio2text_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('knowledges_audio2text_id_fkey', 'knowledges', type_='foreignkey')
    op.drop_constraint('knowledges_video2text_id_fkey', 'knowledges', type_='foreignkey')
    op.drop_column('knowledges', 'video2text_id')
    op.drop_column('knowledges', 'audio2text_id')
    # ### end Alembic commands ###
