"""202511292027

Revision ID: 57c11f3c7aee
Revises: d1e56ecbf058
Create Date: 2025-11-29 20:28:03.325587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c11f3c7aee'
down_revision: Union[str, None] = 'd1e56ecbf058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查表是否存在再添加列
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'data_config') 
               AND NOT EXISTS (SELECT FROM information_schema.columns 
                              WHERE table_name = 'data_config' AND column_name = 'llm') THEN
                ALTER TABLE data_config ADD COLUMN llm VARCHAR;
                COMMENT ON COLUMN data_config.llm IS 'LLM模型配置ID';
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查列是否存在再删除
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT FROM information_schema.columns 
                      WHERE table_name = 'data_config' AND column_name = 'llm') THEN
                ALTER TABLE data_config DROP COLUMN llm;
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###
