"""202511292027

Revision ID: 57c11f3c7aee
Revises: d1e56ecbf058
Create Date: 2025-11-29 20:28:03.325587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c11f3c7aee'
down_revision: Union[str, None] = 'd1e56ecbf058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_config', sa.Column('llm', sa.String(), nullable=True, comment='LLM模型配置ID'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_config', 'llm')
    # ### end Alembic commands ###
