"""202609181630

Revision ID: 5a7336d91b89
Revises: 322df89ac12c
Create Date: 2026-09-18 08:33:18.885009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a7336d91b89'
down_revision: Union[str, None] = '322df89ac12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_executions', sa.Column('agent_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Agent 执行轨迹（AgentTraceRecorder.to_dict 快照：{meta, iterations:[{llm, tool_calls}]}）'))
    op.add_column('agent_executions', sa.Column('parent_execution_id', sa.UUID(), nullable=True, comment='父执行 ID（子 Agent 指向主 Agent 的执行记录；主 Agent 与普通执行为 NULL）'))
    op.add_column('agent_executions', sa.Column('agent_role', sa.String(length=20), server_default='master', nullable=False, comment='执行角色: master（主 Agent）| sub（子 Agent）'))
    op.add_column('agent_executions', sa.Column('orchestration_mode', sa.String(length=20), nullable=True, comment='编排模式: supervisor（主管）| collaboration（协作）；非集群执行时为 NULL'))
    op.create_index(op.f('ix_agent_executions_agent_role'), 'agent_executions', ['agent_role'], unique=False)
    op.create_index(op.f('ix_agent_executions_parent_execution_id'), 'agent_executions', ['parent_execution_id'], unique=False)
    op.create_foreign_key('agent_executions_parent_execution_id_fkey', 'agent_executions', 'agent_executions', ['parent_execution_id'], ['id'], ondelete='SET NULL')
    op.add_column('memory_config', sa.Column('prediction_candidate_limit', sa.Integer(), server_default='8', nullable=False, comment='进入Actor选择池的非主角候选实体数量上限'))
    op.add_column('memory_config', sa.Column('prediction_participant_limit', sa.Integer(), server_default='3', nullable=False, comment='实际参与推演的非主角Actor数量上限'))
    op.add_column('memory_config', sa.Column('prediction_max_steps', sa.Integer(), server_default='4', nullable=False, comment='单次预测推演最大Step数'))
    op.add_column('memory_config', sa.Column('prediction_recall_limit', sa.Integer(), server_default='20', nullable=False, comment='合并筛选后最终入选的记忆数量上限'))
    op.add_column('memory_config', sa.Column('prediction_min_valid_memory_count', sa.Integer(), server_default='3', nullable=False, comment='允许进入EvidenceGate语义判断的最低记忆数量'))
    op.add_column('memory_config', sa.Column('prediction_embedding_min_similarity', sa.Float(), server_default='0.7', nullable=False, comment='Embedding召回最低余弦相似度'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_config', 'prediction_embedding_min_similarity')
    op.drop_column('memory_config', 'prediction_min_valid_memory_count')
    op.drop_column('memory_config', 'prediction_recall_limit')
    op.drop_column('memory_config', 'prediction_max_steps')
    op.drop_column('memory_config', 'prediction_participant_limit')
    op.drop_column('memory_config', 'prediction_candidate_limit')
    op.drop_constraint('agent_executions_parent_execution_id_fkey', 'agent_executions', type_='foreignkey')
    op.drop_index(op.f('ix_agent_executions_parent_execution_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_role'), table_name='agent_executions')
    op.drop_column('agent_executions', 'orchestration_mode')
    op.drop_column('agent_executions', 'agent_role')
    op.drop_column('agent_executions', 'parent_execution_id')
    op.drop_column('agent_executions', 'agent_log')
    # ### end Alembic commands ###
