"""init_db_table

Revision ID: 5de5ec651b01
Revises: b012ab0089b9
Create Date: 2025-11-13 10:11:50.992672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de5ec651b01'
down_revision: Union[str, None] = 'b012ab0089b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_apps_current_release_id', 'apps', 'app_releases', ['current_release_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_apps_current_release_id', 'apps', type_='foreignkey')
    # ### end Alembic commands ###
