"""202606171100

Revision ID: 5f308397855d
Revises: cb7d1a4e9fbb
Create Date: 2026-06-17 11:04:28.852791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f308397855d'
down_revision: Union[str, None] = 'cb7d1a4e9fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('end_users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='是否有效，False 表示已删除'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('end_users', 'is_active')
    # ### end Alembic commands ###
