"""202607171952

Revision ID: 5fb3a976b163
Revises: d487efb5be52
Create Date: 2026-07-17 19:53:12.405262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb3a976b163'
down_revision: Union[str, None] = 'd487efb5be52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_forget_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('end_user_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('trigger', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('recoverable', sa.Boolean(), nullable=False),
    sa.Column('operator', sa.UUID(), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=False),
    sa.Column('is_recovered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['end_user_id'], ['end_users.id'], ),
    sa.ForeignKeyConstraint(['operator'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_forget_log_end_user_id'), 'memory_forget_log', ['end_user_id'], unique=False)
    op.create_index(op.f('ix_memory_forget_log_node_id'), 'memory_forget_log', ['node_id'], unique=False)
    op.create_index(op.f('ix_memory_forget_log_node_type'), 'memory_forget_log', ['node_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_forget_log_node_type'), table_name='memory_forget_log')
    op.drop_index(op.f('ix_memory_forget_log_node_id'), table_name='memory_forget_log')
    op.drop_index(op.f('ix_memory_forget_log_end_user_id'), table_name='memory_forget_log')
    op.drop_table('memory_forget_log')
    # ### end Alembic commands ###
