"""202606171417

Revision ID: 628e0bc42c2d
Revises: 5f308397855d
Create Date: 2026-06-17 06:20:23.419986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628e0bc42c2d'
down_revision: Union[str, None] = '5f308397855d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_context_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='会话ID'),
    sa.Column('scope_key', sa.String(length=255), nullable=False, comment='上下文作用域键'),
    sa.Column('source_type', sa.String(length=32), nullable=False, comment='上下文来源类型：conversation/workflow'),
    sa.Column('summary_text', sa.Text(), nullable=True, comment='滚动摘要文本'),
    sa.Column('summarized_until_message_id', sa.UUID(), nullable=True, comment='应用聊天摘要边界消息ID'),
    sa.Column('summarized_until_at', sa.DateTime(), nullable=True, comment='应用聊天摘要边界时间'),
    sa.Column('summarized_until_seq', sa.BigInteger(), nullable=True, comment='工作流摘要边界序号'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'scope_key', name='uq_conversation_context_state_scope')
    )
    op.create_index(op.f('ix_conversation_context_state_id'), 'conversation_context_state', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_context_state_id'), table_name='conversation_context_state')
    op.drop_table('conversation_context_state')
    # ### end Alembic commands ###
