"""202605272105

Revision ID: 6d84617f847f
Revises: 84b0e88c1316
Create Date: 2026-05-27 21:04:51.588119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d84617f847f'
down_revision: Union[str, None] = '84b0e88c1316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_tool_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('workflow_config_id', sa.UUID(), nullable=False),
    sa.Column('release_id', sa.UUID(), nullable=True),
    sa.Column('input_parameters', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['tool_configs.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['app_releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_tool_configs_app_id'), 'workflow_tool_configs', ['app_id'], unique=False)
    op.create_index(op.f('ix_workflow_tool_configs_release_id'), 'workflow_tool_configs', ['release_id'], unique=False)
    op.add_column('workflow_configs', sa.Column('workflow_type', sa.String(length=20), server_default='workflow', nullable=False))
    op.create_index(op.f('ix_workflow_configs_workflow_type'), 'workflow_configs', ['workflow_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_configs_workflow_type'), table_name='workflow_configs')
    op.drop_column('workflow_configs', 'workflow_type')
    op.drop_index(op.f('ix_workflow_tool_configs_release_id'), table_name='workflow_tool_configs')
    op.drop_index(op.f('ix_workflow_tool_configs_app_id'), table_name='workflow_tool_configs')
    op.drop_table('workflow_tool_configs')
    # ### end Alembic commands ###
