"""202608281820

Revision ID: 6f654269736e
Revises: 2688cd7291ec
Create Date: 2026-08-28 10:20:22.177428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f654269736e'
down_revision: Union[str, None] = '2688cd7291ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogue_emotion_raw',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键（由 dialogue_id 经 uuid5 确定性生成，幂等 Upsert 依据）'),
    sa.Column('dialogue_id', sa.String(length=255), nullable=False, comment='Neo4j Dialogue.id 原始字符串（格式如 Dialog_<uuid>_<n>，非纯 uuid）'),
    sa.Column('end_user_id', sa.UUID(), nullable=False, comment='终端用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='对话原始时刻（naive UTC，不预切日）'),
    sa.Column('emotion', sa.String(length=50), nullable=False, comment='情绪枚举（BERT 十分类英文 code）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dialogue_id')
    )
    op.create_index('idx_dialogue_emotion_raw_user_time', 'dialogue_emotion_raw', ['end_user_id', 'created_at'], unique=False)
    op.create_index('idx_end_users_expiration_scan', 'end_users', ['workspace_id', 'write_time', 'id'], unique=False, postgresql_where=sa.text("is_active = TRUE AND identity_status = 'temporary' AND write_time IS NOT NULL"))
    op.add_column('workspaces', sa.Column('retention_days', sa.Integer(), nullable=True))
    op.create_index('idx_workspaces_retention_enabled', 'workspaces', ['id'], unique=False, postgresql_include=['retention_days'], postgresql_where=sa.text('retention_days IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workspaces_retention_enabled', table_name='workspaces', postgresql_include=['retention_days'], postgresql_where=sa.text('retention_days IS NOT NULL'))
    op.drop_column('workspaces', 'retention_days')
    op.drop_index('idx_end_users_expiration_scan', table_name='end_users', postgresql_where=sa.text("is_active = TRUE AND identity_status = 'temporary' AND write_time IS NOT NULL"))
    op.drop_index('idx_dialogue_emotion_raw_user_time', table_name='dialogue_emotion_raw')
    op.drop_table('dialogue_emotion_raw')
    # ### end Alembic commands ###
