"""202607101421

Revision ID: 72421e202409
Revises: 5211ceecdea4
Create Date: 2026-07-10 14:21:33.728301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72421e202409'
down_revision: Union[str, None] = '5211ceecdea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        "UPDATE memory_config SET pruning_enabled = TRUE "
        "WHERE is_default = TRUE AND (pruning_enabled IS NULL OR pruning_enabled = FALSE)"
    )
    
    op.add_column('memory_messages', sa.Column('pruned_content', sa.Text(), nullable=True, comment='剪枝/规整后内容；NULL=未处理'))
    op.alter_column('memory_messages', 'original_message_id',
               existing_type=sa.UUID(),
               comment='原始消息 ID（对 messages 表的引用；工作流/API/MCP 消息为 NULL）',
               existing_comment='原始消息ID（对 messages 表的引用，工作流消息时为 NULL）',
               existing_nullable=True)
    op.alter_column('memory_messages', 'message_seq',
               existing_type=sa.INTEGER(),
               comment='消息序列编号，从 1 开始，分组键取决于 source：agent/workflow 按 conversation_id；service_api/mcp 按 (end_user_id, source)',
               existing_comment='消息序列编号，从 1 开始，按 conversation_id 维度递增',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memory_messages', 'message_seq',
               existing_type=sa.INTEGER(),
               comment='消息序列编号，从 1 开始，按 conversation_id 维度递增',
               existing_comment='消息序列编号，从 1 开始，分组键取决于 source：agent/workflow 按 conversation_id；service_api/mcp 按 (end_user_id, source)',
               existing_nullable=False)
    op.alter_column('memory_messages', 'original_message_id',
               existing_type=sa.UUID(),
               comment='原始消息ID（对 messages 表的引用，工作流消息时为 NULL）',
               existing_comment='原始消息 ID（对 messages 表的引用；工作流/API/MCP 消息为 NULL）',
               existing_nullable=True)
    op.drop_column('memory_messages', 'pruned_content')
    # ### end Alembic commands ###
