"""202606051036

Revision ID: 7335e9b0e781
Revises: dc7771c5c8bf
Create Date: 2026-06-05 10:36:38.838164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7335e9b0e781'
down_revision: Union[str, None] = 'dc7771c5c8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_metadata_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='租户ID'),
    sa.Column('knowledge_id', sa.UUID(), nullable=False, comment='知识库ID'),
    sa.Column('metadata_id', sa.UUID(), nullable=False, comment='元数据定义ID'),
    sa.Column('document_id', sa.UUID(), nullable=False, comment='文档ID'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='创建人'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_id', 'metadata_id', 'document_id', name='uq_knowledge_metadata_binding')
    )
    op.create_index(op.f('ix_knowledge_metadata_bindings_id'), 'knowledge_metadata_bindings', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_metadata_bindings_knowledge_id'), 'knowledge_metadata_bindings', ['knowledge_id'], unique=False)
    op.create_table('knowledge_metadatas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='租户ID'),
    sa.Column('knowledge_id', sa.UUID(), nullable=False, comment='知识库ID'),
    sa.Column('type', sa.String(), nullable=False, comment='字段类型: string | number | time'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='字段名'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='更新人'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_id', 'name', name='uq_knowledge_metadata_name')
    )
    op.create_index(op.f('ix_knowledge_metadatas_id'), 'knowledge_metadatas', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_metadatas_knowledge_id'), 'knowledge_metadatas', ['knowledge_id'], unique=False)
    op.create_table('workflow_node_caches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('workflow_config_id', sa.UUID(), nullable=True),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=True),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_config_id'], ['workflow_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_node_caches_app_id'), 'workflow_node_caches', ['app_id'], unique=False)
    op.create_index(op.f('ix_workflow_node_caches_cache_key'), 'workflow_node_caches', ['cache_key'], unique=False)
    op.create_index(op.f('ix_workflow_node_caches_id'), 'workflow_node_caches', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_node_caches_node_id'), 'workflow_node_caches', ['node_id'], unique=False)
    op.create_index(op.f('ix_workflow_node_caches_status'), 'workflow_node_caches', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_node_caches_workflow_config_id'), 'workflow_node_caches', ['workflow_config_id'], unique=False)
    op.add_column('documents', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='{field_name: value}'))
    op.add_column('knowledges', sa.Column('builtin_metadata_enabled', sa.Integer(), server_default='0', nullable=False, comment='builtin metadata switch (0: disabled, 1: enabled)'))
    op.alter_column('workflow_node_executions', 'execution_order',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_node_executions', 'execution_order',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('knowledges', 'builtin_metadata_enabled')
    op.drop_column('documents', 'meta_data')
    op.drop_index(op.f('ix_workflow_node_caches_workflow_config_id'), table_name='workflow_node_caches')
    op.drop_index(op.f('ix_workflow_node_caches_status'), table_name='workflow_node_caches')
    op.drop_index(op.f('ix_workflow_node_caches_node_id'), table_name='workflow_node_caches')
    op.drop_index(op.f('ix_workflow_node_caches_id'), table_name='workflow_node_caches')
    op.drop_index(op.f('ix_workflow_node_caches_cache_key'), table_name='workflow_node_caches')
    op.drop_index(op.f('ix_workflow_node_caches_app_id'), table_name='workflow_node_caches')
    op.drop_table('workflow_node_caches')
    op.drop_index(op.f('ix_knowledge_metadatas_knowledge_id'), table_name='knowledge_metadatas')
    op.drop_index(op.f('ix_knowledge_metadatas_id'), table_name='knowledge_metadatas')
    op.drop_table('knowledge_metadatas')
    op.drop_index(op.f('ix_knowledge_metadata_bindings_knowledge_id'), table_name='knowledge_metadata_bindings')
    op.drop_index(op.f('ix_knowledge_metadata_bindings_id'), table_name='knowledge_metadata_bindings')
    op.drop_table('knowledge_metadata_bindings')
    # ### end Alembic commands ###
