"""202602271020

Revision ID: 7672d8f0f939
Revises: 75e28690ae87
Create Date: 2026-02-27 10:21:46.951584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7672d8f0f939'
down_revision: Union[str, None] = '75e28690ae87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_metadata', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='Workspace ID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_metadata', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='Workspace ID')
    # ### end Alembic commands ###
