"""202601121530

Revision ID: 793c31683aa5
Revises: 52ebaf4ad3fb
Create Date: 2026-01-12 15:29:03.135322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793c31683aa5'
down_revision: Union[str, None] = '52ebaf4ad3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_details', sa.Column('question', sa.JSON(), nullable=True, comment='用户问题'))
    op.drop_column('conversation_details', 'theme_intro')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_details', sa.Column('theme_intro', sa.VARCHAR(), autoincrement=False, nullable=True, comment='主题介绍'))
    op.drop_column('conversation_details', 'question')
    # ### end Alembic commands ###
