"""202605151900

Revision ID: 83ba712a9a53
Revises: 4eb827a38506
Create Date: 2026-05-15 19:10:13.789518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ba712a9a53'
down_revision: Union[str, None] = '4eb827a38506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='会话ID'),
    sa.Column('share_uuid', sa.String(length=36), nullable=False, comment='分享唯一标识'),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='工作空间ID'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='创建人ID'),
    sa.Column('password', sa.String(length=100), nullable=True, comment='访问密码（可选）'),
    sa.Column('expire_at', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.Column('allow_copy', sa.Boolean(), nullable=True, comment='是否允许复制内容'),
    sa.Column('view_count', sa.Integer(), nullable=True, comment='访问次数'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否有效'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_uuid')
    )
    op.create_table('message_feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False, comment='消息ID'),
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='会话ID'),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='工作空间ID'),
    sa.Column('user_id', sa.String(), nullable=False, comment='用户ID（EndUser 或 User）'),
    sa.Column('feedback_type', sa.String(length=20), nullable=False, comment='反馈类型: like/dislike'),
    sa.Column('feedback_content', sa.Text(), nullable=True, comment='反馈原因（点踩时填写）'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_feedback')
    )
    op.create_table('message_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False, comment='消息ID'),
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='会话ID'),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='工作空间ID'),
    sa.Column('reported_by', sa.UUID(), nullable=False, comment='举报人ID'),
    sa.Column('report_type', sa.String(length=50), nullable=False, comment='举报类型: politics/porn/violence/fake/ad/quality/other'),
    sa.Column('report_reason', sa.Text(), nullable=True, comment='举报原因详细描述'),
    sa.Column('text_start_offset', sa.Integer(), nullable=True, comment='选中文本起始位置'),
    sa.Column('text_end_offset', sa.Integer(), nullable=True, comment='选中文本结束位置'),
    sa.Column('selected_text', sa.Text(), nullable=True, comment='选中的违规文本片段'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True, comment='状态: pending/reviewing/resolved/rejected'),
    sa.Column('severity', sa.String(length=20), nullable=True, comment='严重程度: low/medium/high/critical'),
    sa.Column('reviewer_id', sa.UUID(), nullable=True, comment='审核人ID'),
    sa.Column('review_note', sa.Text(), nullable=True, comment='审核备注'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('action_taken', sa.String(length=50), nullable=True, comment='处理措施: warning/content_removed/user_banned/no_action'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('messages', sa.Column('version', sa.Integer(), nullable=True, comment='版本号（重新生成时递增）'))
    op.add_column('messages', sa.Column('is_current', sa.Boolean(), nullable=True, comment='是否为当前展示版本'))
    op.add_column('messages', sa.Column('parent_message_id', sa.UUID(), nullable=True, comment='父消息ID（用于重新生成时关联原用户消息）'))
    op.add_column('messages', sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除标记'))
    op.add_column('messages', sa.Column('like_count', sa.Integer(), nullable=True, comment='点赞数'))
    op.add_column('messages', sa.Column('dislike_count', sa.Integer(), nullable=True, comment='点踩数'))
    op.add_column('messages', sa.Column('report_count', sa.Integer(), nullable=True, comment='举报数'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'report_count')
    op.drop_column('messages', 'dislike_count')
    op.drop_column('messages', 'like_count')
    op.drop_column('messages', 'is_deleted')
    op.drop_column('messages', 'parent_message_id')
    op.drop_column('messages', 'is_current')
    op.drop_column('messages', 'version')
    op.drop_table('message_reports')
    op.drop_table('message_feedbacks')
    op.drop_table('conversation_shares')
    # ### end Alembic commands ###
