"""202605221855

Revision ID: 83dbff58c1b6
Revises: b3df241dc051
Create Date: 2026-05-22 18:56:21.506402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83dbff58c1b6'
down_revision: Union[str, None] = 'b3df241dc051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False, comment='应用ID'),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='工作空间ID'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='创建者用户ID'),
    sa.Column('question', sa.Text(), nullable=False, comment='提问'),
    sa.Column('answer', sa.Text(), nullable=False, comment='答案'),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True, comment='提问的Embedding向量'),
    sa.Column('hit_count', sa.Integer(), nullable=False, comment='命中次数'),
    sa.Column('is_active', sa.Integer(), nullable=False, comment='是否激活: 1=是, 0=否'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_annotation_app_active', 'app_annotations', ['app_id', 'is_active'], unique=False)
    op.create_index('idx_annotation_workspace', 'app_annotations', ['workspace_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_app_annotations_app_id'), 'app_annotations', ['app_id'], unique=False)
    op.create_index(op.f('ix_app_annotations_id'), 'app_annotations', ['id'], unique=False)
    op.create_index(op.f('ix_app_annotations_workspace_id'), 'app_annotations', ['workspace_id'], unique=False)
    op.create_table('app_annotation_hit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('annotation_id', sa.UUID(), nullable=False, comment='标注ID'),
    sa.Column('app_id', sa.UUID(), nullable=False, comment='应用ID'),
    sa.Column('source', sa.Text(), nullable=False, comment='来源'),
    sa.Column('query', sa.Text(), nullable=False, comment='用户提问'),
    sa.Column('matched_question', sa.Text(), nullable=False, comment='匹配到的标注问题'),
    sa.Column('answer', sa.Text(), nullable=False, comment='返回的标注答案'),
    sa.Column('similarity', sa.Float(), nullable=False, comment='相似度分数'),
    sa.Column('hit_at', sa.DateTime(), nullable=False, comment='命中时间'),
    sa.ForeignKeyConstraint(['annotation_id'], ['app_annotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hit_log_annotation', 'app_annotation_hit_logs', ['annotation_id', 'hit_at'], unique=False)
    op.create_index('idx_hit_log_app', 'app_annotation_hit_logs', ['app_id', 'hit_at'], unique=False)
    op.create_index(op.f('ix_app_annotation_hit_logs_annotation_id'), 'app_annotation_hit_logs', ['annotation_id'], unique=False)
    op.create_index(op.f('ix_app_annotation_hit_logs_app_id'), 'app_annotation_hit_logs', ['app_id'], unique=False)
    op.create_index(op.f('ix_app_annotation_hit_logs_id'), 'app_annotation_hit_logs', ['id'], unique=False)
    op.create_table('app_annotation_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False, comment='应用ID'),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='工作空间ID'),
    sa.Column('similarity_threshold', sa.Float(), nullable=False, comment='相似度阈值'),
    sa.Column('model_config_id', sa.UUID(), nullable=True, comment='Embedding模型配置ID'),
    sa.Column('enabled', sa.Integer(), nullable=False, comment='是否启用: 1=是, 0=否'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_config_id'], ['model_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_annotation_settings_app_id'), 'app_annotation_settings', ['app_id'], unique=True)
    op.create_index(op.f('ix_app_annotation_settings_id'), 'app_annotation_settings', ['id'], unique=False)
    op.create_index(op.f('ix_app_annotation_settings_workspace_id'), 'app_annotation_settings', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_annotation_settings_workspace_id'), table_name='app_annotation_settings')
    op.drop_index(op.f('ix_app_annotation_settings_id'), table_name='app_annotation_settings')
    op.drop_index(op.f('ix_app_annotation_settings_app_id'), table_name='app_annotation_settings')
    op.drop_table('app_annotation_settings')
    op.drop_index(op.f('ix_app_annotation_hit_logs_id'), table_name='app_annotation_hit_logs')
    op.drop_index(op.f('ix_app_annotation_hit_logs_app_id'), table_name='app_annotation_hit_logs')
    op.drop_index(op.f('ix_app_annotation_hit_logs_annotation_id'), table_name='app_annotation_hit_logs')
    op.drop_index('idx_hit_log_app', table_name='app_annotation_hit_logs')
    op.drop_index('idx_hit_log_annotation', table_name='app_annotation_hit_logs')
    op.drop_table('app_annotation_hit_logs')
    op.drop_index(op.f('ix_app_annotations_workspace_id'), table_name='app_annotations')
    op.drop_index(op.f('ix_app_annotations_id'), table_name='app_annotations')
    op.drop_index(op.f('ix_app_annotations_app_id'), table_name='app_annotations')
    op.drop_index('idx_annotation_workspace', table_name='app_annotations')
    op.drop_index('idx_annotation_app_active', table_name='app_annotations')
    op.drop_table('app_annotations')
    # ### end Alembic commands ###
