"""202605272100

Revision ID: 84b0e88c1316
Revises: 83dbff58c1b6
Create Date: 2026-05-27 21:02:02.287986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b0e88c1316'
down_revision: Union[str, None] = '83dbff58c1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_messages', sa.Column('dialog_at', sa.String(length=64), nullable=True, comment='业务侧会话发生时间（ISO 8601），调用方未提供时为 NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_messages', 'dialog_at')
    # ### end Alembic commands ###
