"""202602041811

Revision ID: 9b28b66cf8e8
Revises: e7c7afa249d1
Create Date: 2026-02-04 18:12:12.454402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b28b66cf8e8'
down_revision: Union[str, None] = 'e7c7afa249d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_configs', 'skill_ids', new_column_name='skills', comment='技能配置')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_configs', 'skills', new_column_name='skill_ids', comment='关联的技能ID列表')
    # ### end Alembic commands ###
