"""202609111720

Revision ID: bf8b73e3f1ef
Revises: 008506effb1a
Create Date: 2026-09-11 09:21:02.583059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8b73e3f1ef'
down_revision: Union[str, None] = '008506effb1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_display_records', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.create_index('idx_memory_display_retrieve_ws_occurred', 'memory_display_records', ['workspace_id', sa.literal_column('occurred_at DESC'), sa.literal_column('id DESC')], unique=False, postgresql_where=sa.text("operation = 'RETRIEVE'"))
    op.create_index('idx_memory_display_write_user_occurred', 'memory_display_records', ['end_user_id', sa.literal_column('occurred_at DESC'), sa.literal_column('id DESC')], unique=False, postgresql_where=sa.text("operation = 'WRITE'"))
    op.create_index('idx_memory_display_write_ws_occurred', 'memory_display_records', ['workspace_id', sa.literal_column('occurred_at DESC'), sa.literal_column('id DESC')], unique=False, postgresql_where=sa.text("operation = 'WRITE'"))
    op.add_column('memory_engine_display_records', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.create_index('idx_engine_display_ws_occurred', 'memory_engine_display_records', ['workspace_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.execute(
        """
        UPDATE memory_display_records AS m
        SET workspace_id = e.workspace_id
        FROM end_users AS e
        WHERE m.end_user_id = e.id
          AND m.workspace_id IS NULL
        """
    )
    op.execute(
        """
        UPDATE memory_engine_display_records AS r
        SET workspace_id = e.workspace_id
        FROM end_users AS e
        WHERE r.end_user_id = e.id
          AND r.workspace_id IS NULL
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_engine_display_ws_occurred', table_name='memory_engine_display_records')
    op.drop_column('memory_engine_display_records', 'workspace_id')
    op.drop_index('idx_memory_display_write_ws_occurred', table_name='memory_display_records', postgresql_where=sa.text("operation = 'WRITE'"))
    op.drop_index('idx_memory_display_write_user_occurred', table_name='memory_display_records', postgresql_where=sa.text("operation = 'WRITE'"))
    op.drop_index('idx_memory_display_retrieve_ws_occurred', table_name='memory_display_records', postgresql_where=sa.text("operation = 'RETRIEVE'"))
    op.drop_column('memory_display_records', 'workspace_id')
    # ### end Alembic commands ###
