"""202606051948

Revision ID: cb7d1a4e9fbb
Revises: 340a8c49e58b
Create Date: 2026-06-05 19:59:43.612858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7d1a4e9fbb'
down_revision: Union[str, None] = '340a8c49e58b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_end_users_workspace_created_desc', 'end_users', ['workspace_id', 'created_at', 'id'], unique=False, postgresql_where='memory_count > 0')
    op.create_index('ix_end_users_workspace_memory', 'end_users', ['workspace_id', 'memory_count'], unique=False, postgresql_where='memory_count > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_end_users_workspace_memory', table_name='end_users', postgresql_where='memory_count > 0')
    op.drop_index('ix_end_users_workspace_created_desc', table_name='end_users', postgresql_where='memory_count > 0')
    # ### end Alembic commands ###
