"""202609031225

Revision ID: cd1237005723
Revises: 6f654269736e
Create Date: 2026-09-03 04:25:43.590940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1237005723'
down_revision: Union[str, None] = '6f654269736e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('end_users', sa.Column('grace_period_until', sa.DateTime(), nullable=True, comment='宽限期截止时间，NULL 表示未触发宽限期'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('end_users', 'grace_period_until')
    # ### end Alembic commands ###
