"""202610101207

Revision ID: d04672399454
Revises: 13040b4dfa6e
Create Date: 2026-10-10 04:08:00.771479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04672399454'
down_revision: Union[str, None] = '13040b4dfa6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_config', sa.Column('batch_trigger_count', sa.Integer(), server_default='20', nullable=False, comment='SceneSummary 社区归类批量触发数量'))
    op.add_column('memory_config', sa.Column('candidate_community_limit', sa.Integer(), server_default='3', nullable=False, comment='单条 SceneSummary 的候选社区数量上限'))
    op.add_column('memory_config', sa.Column('compare_all_same_category_communities', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否比较同一 L1 下全部已有 SceneCommunity'))
    op.add_column('memory_config', sa.Column('rebuild_new_scene_community_count_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否按新增 SceneCommunity 数量触发重建（本期仅存储）'))
    op.add_column('memory_config', sa.Column('rebuild_new_scene_community_count', sa.Integer(), server_default='50', nullable=False, comment='SceneCommunity 重建新增数量（本期仅存储）'))
    op.add_column('memory_config', sa.Column('rebuild_interval_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否按时间间隔触发 SceneCommunity 重建（本期仅存储）'))
    op.add_column('memory_config', sa.Column('rebuild_interval_days', sa.Integer(), server_default='1', nullable=False, comment='SceneCommunity 重建时间间隔天数（本期仅存储）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_config', 'rebuild_interval_days')
    op.drop_column('memory_config', 'rebuild_interval_enabled')
    op.drop_column('memory_config', 'rebuild_new_scene_community_count')
    op.drop_column('memory_config', 'rebuild_new_scene_community_count_enabled')
    op.drop_column('memory_config', 'compare_all_same_category_communities')
    op.drop_column('memory_config', 'candidate_community_limit')
    op.drop_column('memory_config', 'batch_trigger_count')
    # ### end Alembic commands ###
