"""202607101900

Revision ID: d487efb5be52
Revises: 72421e202409
Create Date: 2026-07-10 18:59:07.439323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd487efb5be52'
down_revision: Union[str, None] = '72421e202409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_messages', sa.Column('topic_entity_hint', sa.String(length=512), nullable=True, comment='LLM 剪枝产出的实体锚点（processed_user_topic_entity_hint）；NULL=未剪枝或无锚点'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_messages', 'topic_entity_hint')
    # ### end Alembic commands ###
