"""202608071204

Revision ID: dae70859b388
Revises: 2a50ba49c523
Create Date: 2026-08-07 04:05:26.315312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae70859b388'
down_revision: Union[str, None] = '2a50ba49c523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('end_user_merge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('origin_id', sa.UUID(), nullable=True, comment='原始end_user_id'),
    sa.Column('origin_other_id', sa.String(), nullable=False, comment='原始end_user other_id'),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_end_user_merge_id'), 'end_user_merge', ['id'], unique=False)
    op.create_index(op.f('ix_end_user_merge_origin_id'), 'end_user_merge', ['origin_id'], unique=False)
    op.create_index(op.f('ix_end_user_merge_origin_other_id'), 'end_user_merge', ['origin_other_id'], unique=False)
    op.create_index(op.f('ix_end_user_merge_target_id'), 'end_user_merge', ['target_id'], unique=False)
    op.create_index(op.f('ix_end_user_merge_workspace_id'), 'end_user_merge', ['workspace_id'], unique=False)
    op.add_column('api_keys', sa.Column('rate_limit_disabled', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='跳过全部限流检查（预置服务 Key 专用）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'rate_limit_disabled')
    op.drop_index(op.f('ix_end_user_merge_workspace_id'), table_name='end_user_merge')
    op.drop_index(op.f('ix_end_user_merge_target_id'), table_name='end_user_merge')
    op.drop_index(op.f('ix_end_user_merge_origin_other_id'), table_name='end_user_merge')
    op.drop_index(op.f('ix_end_user_merge_origin_id'), table_name='end_user_merge')
    op.drop_index(op.f('ix_end_user_merge_id'), table_name='end_user_merge')
    op.drop_table('end_user_merge')
    # ### end Alembic commands ###
