"""202606031853

Revision ID: dc7771c5c8bf
Revises: 6d84617f847f
Create Date: 2026-06-03 18:53:34.199494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc7771c5c8bf'
down_revision: Union[str, None] = '6d84617f847f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_configs', sa.Column('environment_variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_configs', 'environment_variables')
    # ### end Alembic commands ###
