"""202605221150

Revision ID: e689c2ed3438
Revises: 1620abe078cf
Create Date: 2026-05-22 11:59:37.929425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e689c2ed3438'
down_revision: Union[str, None] = '1620abe078cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='会话ID（Agent对话和工作流消息均使用此字段）'),
    sa.Column('original_message_id', sa.UUID(), nullable=True, comment='原始消息ID（对 messages 表的引用，工作流消息时为 NULL）'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: user/assistant/system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('message_seq', sa.Integer(), nullable=False, comment='消息序列编号，从 1 开始，按 conversation_id 维度递增'),
    sa.Column('should_memorize', sa.Boolean(), nullable=False, comment='是否需要记忆写入；FALSE 时跳过 Write_Pipeline 但 write_cursor 继续推进'),
    sa.Column('files', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment="文件信息列表，FileInput.model_dump(mode='json')"),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['original_message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_messages_conv_seq', 'memory_messages', ['conversation_id', 'message_seq'], unique=False)
    op.create_index(op.f('ix_memory_messages_id'), 'memory_messages', ['id'], unique=False)
    op.add_column('conversations', sa.Column('write_cursor', sa.Integer(), server_default='0', nullable=False, comment='最后一条已处理的 memory_messages 表中消息的 message_seq；should_memorize=FALSE 时也推进'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'write_cursor')
    op.drop_index(op.f('ix_memory_messages_id'), table_name='memory_messages')
    op.drop_index('idx_memory_messages_conv_seq', table_name='memory_messages')
    op.drop_table('memory_messages')
    # ### end Alembic commands ###
