"""202603131452

Revision ID: ea31b4e347d8
Revises: 01587a13522f
Create Date: 2026-03-13 14:53:20.587580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea31b4e347d8'
down_revision: Union[str, None] = '01587a13522f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_shares', sa.Column('permission', sa.String(), nullable=False, comment='权限模式: readonly | editable'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_shares', 'permission')
    # ### end Alembic commands ###
