"""202603131800

Revision ID: ef9d172cb753
Revises: ea31b4e347d8
Create Date: 2026-03-13 18:01:11.167711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9d172cb753'
down_revision: Union[str, None] = 'ea31b4e347d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_shares', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='是否有效，False 表示逻辑删除'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_shares', 'is_active')
    # ### end Alembic commands ###
