"""202607231107

Revision ID: f33568f8aa8f
Revises: 5fb3a976b163
Create Date: 2026-07-23 03:11:15.550748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f33568f8aa8f'
down_revision: Union[str, None] = '5fb3a976b163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('end_users', sa.Column('memory_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='用户名片Tag字符串数组'))
    op.add_column('end_users', sa.Column('memory_tags_updated_at', sa.DateTime(), nullable=True, comment='用户名片Tag最后成功生成或源指纹检查时间'))
    op.add_column('end_users', sa.Column('memory_tags_source_fingerprint', sa.String(length=64), nullable=True, comment='用户名片Tag清洗后源数据SHA-256指纹'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('end_users', 'memory_tags_source_fingerprint')
    op.drop_column('end_users', 'memory_tags_updated_at')
    op.drop_column('end_users', 'memory_tags')
    # ### end Alembic commands ###
