"""202606232120

Revision ID: f91c935a4776
Revises: 628e0bc42c2d
Create Date: 2026-06-23 21:24:11.775992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91c935a4776'
down_revision: Union[str, None] = '628e0bc42c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('end_users', sa.Column('write_time', sa.DateTime(), nullable=True, comment='最后一次记忆写入时间'))
    # ### end Alembic commands ###
    conn = op.get_bind()

    # 2. 回填：有会话的用户取其 conversations.updated_at 最大值；无会话的用户不回填（保持 NULL）。
    #    conversations.user_id 为 String，end_users.id 为 UUID，需 ::text 转换后关联。
    backfill = conn.execute(sa.text("""
        UPDATE end_users eu
        SET write_time = sub.max_updated
        FROM (
            SELECT user_id, MAX(updated_at) AS max_updated
            FROM conversations
            WHERE user_id IS NOT NULL
            GROUP BY user_id
        ) sub
        WHERE eu.id::text = sub.user_id
          AND sub.max_updated IS NOT NULL
    """))
    print(f"[write_time] 已回填用户数量: {backfill.rowcount}")

    # 3. 打开工作空间默认配置中仍关闭的反思引擎开关
    result = conn.execute(sa.text("""
        UPDATE memory_config
        SET enable_self_reflexion = true,
            updated_at = (now() at time zone 'utc')
        WHERE is_default = true
          AND enable_self_reflexion = false
    """))
    print(f"[enable_self_reflexion] 已更新工作空间默认配置数量: {result.rowcount}")

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('end_users', 'write_time')
    # ### end Alembic commands ###
